MusicApp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :bands, only: [:new, :create, :edit, :show, :update, :destroy, :index]
end

MusicApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MusicApp/app/models/band.rb
class Band < ApplicationRecord
    validates :name, presence: true

    
end

MusicApp/app/models/user.rb
class User < ApplicationRecord
    validates :email, presence: true
    validates :session_token, presence: true, uniqueness: true
    validates :password_digest, presence: true

    after_initialize :ensure_session_token
    
    attr_reader :password
    
    def self.find_by_credentials (email, password)
        @user = User.find_by(email: email, password: password)
        
        return nil unless @user && @user.is_password?(password)
        user
    end
    
    def self.generate_session_token
        SecureRandom::urlsafe_base64
    end

    def reset_session_token!
        self.update!(session_token: self.class.generate_session_token)
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= self.class.generate_session_token
    end

    def is_password?(password)
        bcrypt_password = BCrypt::Password(self.password_digest)
        bcrypt_password.is_password?(password)
    end

    def password=(password)
        @password = password
        
        self.password_digest = BCrypt::Password.create(password)
    end


end

MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def logged_in?
        !!current_user
    end

    def log_in_user! (user)
        session[:session_token] = user.reset_session_token!
        @current_user = user
    end

    helper_method :current_user, :logged_in?

end

MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController

    def index
        @bands = Band.all.includes(:name)
        render :index
    end

    def new
        @band = Band.new
        render :new
    end

    def edit
        @band = Band.find(params[:id])
        render :edit
    end

    def create
        @band = Band.new(band_params)

        if @band
            redirect_to bands_url(@band)
        else
            flash.now[:errors] = @band.errors.full_messages
            render :new
        end
    end

    def show
        @band = Band.find_by(name: params[:name])

        if @band
            render :show
        else
            redirect_to bands_url
        end

    end

    def destroy
        @band = Band.find(params[:id])
        @band.destroy
        redirect_to bands_url
    end

    def update
        @band = Band.find(params[:id])

        if @band.update(band_params)
            redirect_to bands_url(@band)
        else
            flash.now[:errors] = @band.errors.full_messages
            render :edit
        end
    end

    private

    def band_params
        params.require(:band).permit(:name)
    end

end

MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        render :new
    end

    def create
        user = User.find_by_credentials(params[:user][:email], params[:user][:password])

        if user
            login!(user)
            redirect_to users_url
        else
            flash.now[:errors] = ["Invalid Name or Password"]
            render :new
        end
    end

    def destroy
        logout!
        redirect_to new_session_url
    end

end

MusicApp/app/controllers/users_controller.rb
require 'byebug'

class UsersController < ApplicationController

    def new
        @user = User.new
        render :new
    end

    def create
        debugger
        
        @user = User.new(user_params)
        if @user
            debugger
            login!(@user)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = @users.error.full_messages
            render :new
        end
    end

    def show
        render :show
    end

    private

    def user_params
        params.require(:user).permit(:email, :password_digest, :session_token)
    end

end

MusicApp/app/helpers/application_helper.rb
module ApplicationHelper
end

MusicApp/app/views/bands/destroy.html.erb
<label = ""> </label>

MusicApp/app/views/bands/edit.html.erb
<h1>Edit band</h1>
<%= form :render, band: @band%>

MusicApp/app/views/bands/index.html.erb
<h1>All bands</h1>

<% @bands.each do |band|%>
<%= band.name%>
<a href="<% bands_url(band)%>" >Show band</a>

MusicApp/app/views/bands/new.html.erb
<h1 name="page header">New Band</h1>

<a class='button' href=<%new_session_url%>>Go to sign-in </a>

<form class="for" action="<% bands_url %>" method="POST">

<p>
    <label for="new-band-name">Name</label>
    <input id="new-band-name" type="text" name="band[name]">
</p>

<input type="submit" value="Submit">

MusicApp/app/views/bands/show.html.erb
<h1>Show Page</h1>
<p><%= band.name %></p>

<form method="POST" action="<%band_url(@user)%>">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" value="Delete band">

MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1 class='main-logo'>Music App</h1>

      <% if logged_in? %>
        <nav>
          <a class='button' href="<%= bands_url %>">Take me Home</a>
          
          <div class='user-detail'>
            <p>Logged in as: <%= current_user.email %></p>
          <form action=<%= session_url %> method='post'>
            <input
              type="hidden"
              name="_method"
              value="delete">
            <input
              type="hidden"
              name="authenticity_token"
              value="<%= form_authenticity_token %>">
            <input 
              type="submit" value="Sign Out">
          </form>
          </div>
        </nav>
      <% end %>

      <% if flash[:notice] %>
        <p><%= flash[:notice] %></p>
      <% end %>

      <% if flash[:errors] %>
        <p><%= flash[:errors].join(", ") %></p>
      <% end %>



    <%= yield %>
  </body>
</html>

MusicApp/app/views/users/new.html.erb
<h1 name="page header">New User</h1>

<a class='button' href=<%new_session_url%>>Go to sign-in </a>
<input type="hidden" name="authenticity_token" value="<% form_authenticity_token%>">



<form class="for" action="<% users_url %>" method="POST">

<p>
    <label for="new-user-email">Email</label>
    <input id="new-user-email" type="text" name="user[email]">
</p>

<p>
    <label for="new-user-password">Password</label>
    <input id="new-user-password" type= "text" name="user[password]">
</p>

<input type="submit" value="Submit">

MusicApp/app/views/users/show.html.erb
<h1 class="Page header">User profile</h1>

<p>
    Email: <%= current_user.email %>
</p>